### PR TITLE
Author archives 

### PR DESCRIPTION
**Pull request by Shelob9**
#15 @royboy789 Can you please review/correct and make pagination work? Also, am I updating Posts factory wrong?

### CODE REVIEW

**Comment by royboy789** [comment]
@Shelob9 there is a fundamental flaw with this that I haven't tested. If we are going to use the same localstorage object, it will add posts (pagination) and push new posts, so when you go back to the list view it will have added just the author's posts vs. all authors. Either need to create a new factory, or make $http requests instead of using the factory.

**Comment by royboy789** [comment]
This is a duct tape solution for now. It works, it grabs the posts and does pagination, however we need to think of an overall gameplan that works with LocalStorage.. 'cause why not? Do we create a new object for each other, do we cycle through the current Local wp.posts object first and pick out the author we want? further discussion required.. merging pull request for now

**Comment by Shelob9** [comment]
Couldn't we key the local storage by type of archive?

**Comment by Shelob9** [comment]
You're right this is a fundamental flaw, and it's going to get worse when we throw in other post types. Current system can't account for post type or for type of archive being stored or anything about that query that created that archive ...

Right now setting in local storage is like this: `localStorageService.set( 'posts', posts_res );`

Couldn't we key by post type and archive type?

For posts of post type post on main index:
`localStorageService.set( 'posts.post.main', posts_res );`

or

For posts of post type post on author archive where author ID = 1:
`localStorageService.set( 'posts.post.author.1', posts_res );`

or

For posts of product type post on term archive where term ID = 7:
`localStorageService.set( 'posts.product.term.7', posts_res );`

For local storage service to be very useful it needs to be able to get/set ALL the types of queries, way too simplistic right now.

**Comment by royboy789** [comment]
I need to see if we can set post object objects (posts.XXXXX) but we can set it up like that.
posts.[post_type]
posts.author.[id]
posts.term.[term]
--- but what does that equate to performance with a lot of duplicate content?

**Comment by Shelob9** [comment]
Your indexing proposal doesn't take into account post type in the archives, always prefix with post type:

posts.[post_type]
posts.[post_type].author.[id]
posts.[post_type].term.[term]

Of course term archives could be for multiple post types, same with author post types. Hmm, just not trying to be short sighted here, don't like having to rewrite things when a layer of complication we could have seen coming is introduced.

`--- but what does that equate to performance with a lot of duplicate content?`
Yes it will, but we're doing the simple version here, and preventing duplications is fucking complicated, and doing it without all sorts of extra HTTP requests is either impossible/ going to take me some time to figure out, so just ignore that for now beacuse I have a scheme to make that irrelevant that might be BS, or might be smart give me a minute.

**Comment by royboy789** [comment]
the totalPosts still requires a HTTP call. only real benefit is if you have page 2+ stored locally, every time requires a HTTP call to make sure that you have the latest total post count (so you know how many total pages)

**Comment by royboy789** [comment]
testing out in the author-archives branch.. posts.posts does work, so posts.[post-type] could also work, but we'll have to change the factory to be more CPT agnostic. 

I also need to start breaking apart this JS file, its getting annoying.

**Comment by Shelob9** [comment]
Yes, totalPosts requires an HTTP call, but so does putting data into localStorage. My goal is three things:

1) Always have next page in local storage, even if that sets off an HTTP call to get next, next page fine.
2) Loading page the second time should make no HTTP: better performance, less load on API server, less worry that API server might be down, and less worry that internet connection is down.
3) I want to have as many single post types in localStorage so that we shouldn't have to do a redundant call to API server to get the data we already have, even if we're not clicking into it from archive were all that data is already in `$scope`. 
4) When we add the "add for offline reading button" #2 it probably will not have to do anything besides check and see if we already have the post locally which we almost always will.

And yes, cache invalidation and updating total posts is complicated. Version 1.

**Comment by royboy789** [comment]
going to create an issue to continue conversation.

**Pull request merged**
